export enum CommandType {
  ActuatorToggleCommand = 'ActuatorToggleCommand',
  ActuatorSetStateCommand = 'ActuatorSetStateCommand',
  ActuatorRestoreTargetAutomaticValueCommand = 'ActuatorRestoreTargetAutomaticValueCommand',
  DimmerSetLightCommand = 'DimmerSetLightCommand',
  FloorSetAllShuttersCommand = 'FloorSetAllShuttersCommand',
  LampSetLightCommand = 'LampSetLightCommand',
  LampSetTimeBasedCommand = 'LampSetTimeBasedCommand',
  LampToggleLightCommand = 'LampToggleLightCommand',
  LedSetLightCommand = 'LedSetLightCommand',
  RoomRestoreShutterPositionCommand = 'RoomRestoreShutterPositionCommand',
  ShutterSetLevelCommand = 'ShutterSetLevelCommand',
  ShutterSunriseUpCommand = 'ShutterSunriseUpCommand',
  SunsetDownCommand = 'SunsetDownCommand',
  WindowRestoreDesiredPositionCommand = 'WindowRestoreDesiredPositionCommand',
  WindowSetDesiredPositionCommand = 'WindowSetDesiredPositionCommand',
  WindowSetRolloByWeatherStatusCommand = 'WindowSetRolloByWeatherStatusCommand',
}
