export enum DeviceClusterType {
  all = 0,
  Buttons = 1,
  Heater = 2,
  LED = 3,
  Lamps = 4,
  MotionDetection = 5,
  Outlets = 6,
  PresenceDetection = 7,
  Speaker = 8,
  SmokeDetector = 9,
  WaterDetectors = 10,
  Windows = 11,
  Handle = 12,
  Vibration = 13,
  Shutter = 14,
  MagnetContact = 15,
  TemperaturSensor = 16,
  HumiditySensor = 17,
  Ac = 18,
  WLED = 19,
}
