export enum DeviceCapability {
  ac = 0,
  actuator = 1,
  buttonSwitch = 2,
  energyManager = 3,
  excessEnergyConsumer = 4,
  heater = 5,
  humiditySensor = 6,
  illuminationSensor = 7,
  lamp = 8,
  dimmablelamp = 9,
  motionSensor = 10,
  shutter = 11,
  temperatureSensor = 12,
  vibrationSensor = 13,
  speaker = 14,
  handleSensor = 15,
  batteryDriven = 16,
}
