on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  npm-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22'
      - run: npm install
      - run: npm run test
